### ISSUE TITLE
mat.yaml

### ISSUE THREAD

**Issue by changykang** [boschresearch/meta-adversarial-training#1]
hello author,i change the configs/mat.yaml file optimizer: !!python/object:config.OptimizerConfig to optimizer: !!str config.OptimizerConfig. when i run the mat/train.py, it shown 
Traceback (most recent call last):
  File "mat/train.py", line 233, in <module>
    main()
  File "mat/train.py", line 220, in main
    config = PatchTrainingConfig.from_yaml(args.config)
  File "E:\adversarial_defense_paper\4\meta-adv-training\meta-adversarial-training-master\mat\config.py", line 49, in from_yaml
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'min_step_size'
So, can you help me to solve this problem? thank you.

**Comment by jmetzen** [comment]
Hello changykang, 
the error is due to your change `configs/mat.yaml`. With the original config, it is specified that an object of type `config.OptimizerConfig` is to be created, with your change a different type of object is tried to be created (presumably a string, haven't checked). So please undo this change and it should work. Or was there a particular reason for this change?
